# This configuration was used Ebert to review the alfert/baumeister repository
# on 5690b92fe01a16122d4ba43bac48797b76197057.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: plataformatec/linters
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- cover
- node_modules
- apps/baumeister_web/priv/static
subapps:
  - baumeister_web
    path: apps/baumeister_web
    engines:
      credo:
        enabled: true
      eslint:
        enabled: true
      csslint:
        enabled: true
    excluded_paths:
      - priv/static
      - web/static/vendor
  - baumeister_core
    path: apps/baumeister_core
  - baumeister_worker
    path: apps/baumeister_worker
  - baumeister_coordinator
    path: apps/baumeister_coordinator
