language: elixir
notifications:
  recipients:
    - klaus.alfert@gmail.com
otp_release:
  - 19.0
elixir:
  - 1.3.4
before_script:
  - mix local.hex --force
  - mix local.rebar
script: "MIX_ENV=test mix do deps.get, deps.compile, test"
#after_script:
#  - MIX_ENV=docs mix deps.get
#  - MIX_ENV=docs mix inch.report
